OfficeBundle\Entity\DayType:
    type: entity
    table: null
    repositoryClass: OfficeBundle\Repository\DayTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        data:
            type: text
            nullable: true
        name:
            type: string
            nullable: false
        count:
            type: integer
            nullable: false
        isDeleted:
            type: boolean
    lifecycleCallbacks: {  }
