OfficeBundle\Entity\UserPresence:
    type: entity
    table: null
    repositoryClass: OfficeBundle\Repository\UserPresenceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        userId:
            targetEntity: UserPersonal
            inversedBy: presence
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
    fields:
        date:
            type: datetime
            nullable: false
        state:
            type: integer
            nullable: false
        description:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
